import { Profile, Project, Skill, TimelineEvent, AnalyticsSummary } from '../../../Portfolio/shared/types';

export const mockProfile: Profile = {
  name: 'SERGIO JÁUREGUI',
  title: 'FULL STACK DEVELOPER',
  tagline: 'Desarrollador Full Stack con experiencia en automatización, tecnología escalable y estrategia para generar valor de negocio',
  bio: 'Desarrollador Full Stack especializado en crear soluciones tecnológicas escalables y automatizadas. Experiencia en dirección técnica, liderazgo de equipos y desarrollo de aplicaciones web integradas con IA. Apasionado por la innovación y la optimización de procesos.',
  availability: 'available',
  location: 'Chile / Remote',
  email: 'sergiojauregui22@gmail.com',
  socials: {
    github: 'https://github.com/sergiojauregui',
    linkedin: 'https://linkedin.com/in/sergio-jauregui',
    twitter: 'https://twitter.com/sergiojauregui',
  },
};

export const mockProjects: Project[] = [
  // Proyectos Principales
  {
    id: '1',
    slug: 'owozu',
    title: 'OWOZU',
    description: 'Plataforma de estadísticas en tiempo real de creadores de contenido',
    longDescription:
      'OWOZU es una plataforma que muestra estadísticas en tiempo real de creadores de contenido (YouTube, Twitch, etc.) mediante integraciones con APIs. Incluye optimización SEO, lazy loading y diseño responsive.',
    image: '/images/projects/owozu.jpg',
    tech: ['JavaScript', 'WordPress', 'PHP', 'MySQL', 'API REST', 'Elementor', 'SEO', 'SSL'],
    category: 'web',
    featured: true,
    order: 1,
    demoUrl: 'https://owozu.com',
    metrics: {
      performance: 92,
      accessibility: 88,
      seo: 95,
    },
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    slug: 'venecian-flower',
    title: 'Venecian Flower - Floristería Online',
    description: 'E-commerce de productos florales con pasarela de pago',
    longDescription:
      'Venecian Flower es un e-commerce de productos florales. El sitio incluye integración con pasarelas de pago seguras y un sistema de gestión de inventario en tiempo real. UX/UI fluido en dispositivos móviles y de escritorio.',
    image: '/images/projects/venecian-flower.jpg',
    tech: ['JavaScript', 'WordPress', 'PHP', 'MySQL', 'Elementor', 'SEO', 'SSL'],
    category: 'web',
    featured: true,
    order: 2,
    demoUrl: 'https://floristeriavenecianflower.com/',
    metrics: {
      performance: 90,
      accessibility: 92,
      seo: 93,
    },
    createdAt: '2023-11-20T00:00:00Z',
  },
  {
    id: '3',
    slug: 'siu-tutuava',
    title: 'Siu Tutuava - E-commerce Servicios Naturales',
    description: 'E-commerce de productos y servicios naturales',
    longDescription:
      'Siu Tutuava es un e-commerce que promueve y vende productos y servicios naturales. La plataforma permite la visualización de catálogos de productos naturales, con Landing Pages exclusivas con un diseño centrado en la experiencia del usuario.',
    image: '/images/projects/siu-tutuava.jpg',
    tech: ['JavaScript', 'WordPress', 'PHP', 'MySQL', 'Elementor', 'SEO', 'SSL', 'SEM'],
    category: 'web',
    featured: true,
    order: 3,
    demoUrl: 'https://siu-tutuava.com',
    metrics: {
      performance: 91,
      accessibility: 90,
      seo: 94,
    },
    createdAt: '2023-09-10T00:00:00Z',
  },
  // Proyectos de Práctica
  {
    id: '4',
    slug: 'mi-blog-app',
    title: 'Mi Blog App',
    description: 'Aplicación de blog con CRUD completo',
    longDescription:
      'Aplicación web para crear, leer, actualizar y eliminar artículos de blog. Construida con React, Node.js y TypeScript, con un diseño moderno usando Tailwind CSS.',
    image: '/images/projects/blog-app.jpg',
    tech: ['Node.js', 'React', 'TypeScript', 'Tailwind CSS'],
    category: 'fullstack',
    featured: false,
    order: 4,
    demoUrl: 'https://mi-blog-app.netlify.app/',
    repoUrl: 'https://github.com/SergioAngel-1/blog-app/tree/BlogAdministrableV.1',
    metrics: {
      performance: 88,
      accessibility: 85,
      seo: 82,
    },
    createdAt: '2024-03-05T00:00:00Z',
  },
  {
    id: '5',
    slug: 'rick-and-morty-api',
    title: 'Rick And Morty API',
    description: 'Visualización de personajes mediante API oficial',
    longDescription:
      'Aplicación web que consume la API oficial de Rick and Morty para visualizar personajes de la serie. Incluye búsqueda, filtros y diseño responsive.',
    image: '/images/projects/rick-morty.jpg',
    tech: ['TypeScript', 'React', 'API REST', 'Tailwind', 'Netlify'],
    category: 'web',
    featured: false,
    order: 5,
    demoUrl: 'https://rickandmortyapiconsumed.netlify.app/',
    repoUrl: 'https://github.com/SergioAngel-1/rickandmorty',
    metrics: {
      performance: 90,
      accessibility: 87,
      seo: 80,
    },
    createdAt: '2023-08-15T00:00:00Z',
  },
  {
    id: '6',
    slug: 'idbm-search-movie',
    title: 'IDBM Search Movie',
    description: 'Buscador de películas con API IMDB',
    longDescription:
      'Buscador de películas y sus características por medio de la API IMDB. Permite buscar información detallada de películas, actores y ratings.',
    image: '/images/projects/movie-search.jpg',
    tech: ['TypeScript', 'React', 'API REST', 'Tailwind', 'IMDB API'],
    category: 'web',
    featured: false,
    order: 6,
    demoUrl: 'https://moviesearchibdm.netlify.app/',
    repoUrl: 'https://github.com/SergioAngel-1/idbm-movie-api',
    metrics: {
      performance: 89,
      accessibility: 86,
      seo: 81,
    },
    createdAt: '2023-07-20T00:00:00Z',
  },
  {
    id: '7',
    slug: 'pinup',
    title: 'PINUP',
    description: 'Aplicación web para academia de baile',
    longDescription:
      'Aplicación Web para academia de baile, con roles, perfiles, autenticación JWT y sistema de correos. Incluye gestión de usuarios y clases.',
    image: '/images/projects/pinup.jpg',
    tech: ['React', 'JavaScript', 'Node.js', 'Email.js', 'JWT', 'MySQL'],
    category: 'fullstack',
    featured: false,
    order: 7,
    demoUrl: 'https://pinup-7bs6.onrender.com/',
    repoUrl: 'https://github.com/SergioAngel-1/PINUP',
    metrics: {
      performance: 85,
      accessibility: 83,
      seo: 78,
    },
    createdAt: '2023-06-10T00:00:00Z',
  },
  {
    id: '8',
    slug: 'admin-estudiantes',
    title: 'Administrador de Estudiantes',
    description: 'CRUD con Express.js y motor de plantillas EJS',
    longDescription:
      'Sistema para crear, leer, actualizar y eliminar estudiantes. Construido con Express.js, motor de plantillas EJS y base de datos SQLite.',
    image: '/images/projects/crud-students.jpg',
    tech: ['Node.js', 'Express.js', 'SQLite', 'EJS', 'Bootstrap'],
    category: 'fullstack',
    featured: false,
    order: 8,
    demoUrl: 'https://admin-students-express-js.onrender.com/students',
    repoUrl: 'https://github.com/SergioAngel-1/Admin-Students-Express-JS',
    metrics: {
      performance: 87,
      accessibility: 84,
      seo: 75,
    },
    createdAt: '2023-05-15T00:00:00Z',
  },
  {
    id: '9',
    slug: 'admin-productos',
    title: 'Administrador de Productos',
    description: 'CRUD con Maven y Spring Boot',
    longDescription:
      'Sistema para crear, leer, actualizar y eliminar productos. Construido con Maven, Java, Spring Boot y frontend en HTML con Bootstrap.',
    image: '/images/projects/crud-products.jpg',
    tech: ['Maven', 'Java', 'Spring Boot', 'Bootstrap', 'JavaScript'],
    category: 'fullstack',
    featured: false,
    order: 9,
    demoUrl: 'https://crud-products-springboot-java.onrender.com/',
    repoUrl: 'https://github.com/SergioAngel-1/CRUD-Products-Springboot-Java',
    metrics: {
      performance: 86,
      accessibility: 82,
      seo: 74,
    },
    createdAt: '2023-04-20T00:00:00Z',
  },
  {
    id: '10',
    slug: 'portfolio-sergio-jauregui',
    title: 'Portafolio Sergio Jáuregui',
    description: 'Portafolio personal de proyectos',
    longDescription:
      'Portafolio de mis proyectos hechos como Desarrollador Web. Construido con React, Next.js, TypeScript, Tailwind CSS y Framer Motion.',
    image: '/images/projects/portfolio.jpg',
    tech: ['React', 'TypeScript', 'Tailwind', 'Next.js', 'Email.js', 'Framer Motion'],
    category: 'web',
    featured: false,
    order: 10,
    demoUrl: 'https://portfolio-khof.onrender.com/',
    repoUrl: 'https://github.com/SergioAngel-1/portfolio',
    metrics: {
      performance: 95,
      accessibility: 92,
      seo: 90,
    },
    createdAt: '2024-02-10T00:00:00Z',
  },
];

export const mockSkills: Skill[] = [
  // Frontend
  {
    id: 's1',
    name: 'React',
    category: 'frontend',
    proficiency: 90,
    yearsOfExperience: 3,
    relatedProjects: ['1', '2'],
    color: '#00BFFF',
  },
  {
    id: 's2',
    name: 'Next.js',
    category: 'frontend',
    proficiency: 88,
    yearsOfExperience: 2,
    relatedProjects: ['1', '3'],
    color: '#00BFFF',
  },
  {
    id: 's3',
    name: 'Vue.js',
    category: 'frontend',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['2'],
    color: '#00BFFF',
  },
  {
    id: 's4',
    name: 'TypeScript',
    category: 'frontend',
    proficiency: 92,
    yearsOfExperience: 3,
    relatedProjects: ['1', '3', '4'],
    color: '#00BFFF',
  },
  {
    id: 's5',
    name: 'Tailwind CSS',
    category: 'frontend',
    proficiency: 90,
    yearsOfExperience: 2,
    relatedProjects: ['1', '2'],
    color: '#00BFFF',
  },
  {
    id: 's6',
    name: 'JavaScript (ES6+)',
    category: 'frontend',
    proficiency: 95,
    yearsOfExperience: 3,
    relatedProjects: ['1', '2', '3'],
    color: '#00BFFF',
  },
  // Backend
  {
    id: 's7',
    name: 'Node.js',
    category: 'backend',
    proficiency: 90,
    yearsOfExperience: 3,
    relatedProjects: ['1', '2', '4'],
    color: '#FF4500',
  },
  {
    id: 's8',
    name: 'NestJS',
    category: 'backend',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['1'],
    color: '#FF4500',
  },
  {
    id: 's9',
    name: 'Laravel',
    category: 'backend',
    proficiency: 88,
    yearsOfExperience: 2,
    relatedProjects: ['3'],
    color: '#FF4500',
  },
  {
    id: 's10',
    name: 'Django',
    category: 'backend',
    proficiency: 82,
    yearsOfExperience: 1,
    relatedProjects: ['4'],
    color: '#FF4500',
  },
  {
    id: 's11',
    name: 'Express',
    category: 'backend',
    proficiency: 90,
    yearsOfExperience: 3,
    relatedProjects: ['2'],
    color: '#FF4500',
  },
  {
    id: 's12',
    name: 'PostgreSQL',
    category: 'backend',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['1', '3'],
    color: '#FF4500',
  },
  {
    id: 's13',
    name: 'MySQL',
    category: 'backend',
    proficiency: 88,
    yearsOfExperience: 3,
    relatedProjects: ['2', '3'],
    color: '#FF4500',
  },
  {
    id: 's14',
    name: 'MongoDB',
    category: 'backend',
    proficiency: 80,
    yearsOfExperience: 2,
    relatedProjects: ['2'],
    color: '#FF4500',
  },
  // DevOps & Cloud
  {
    id: 's15',
    name: 'Docker',
    category: 'devops',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['1'],
    color: '#FF0000',
  },
  {
    id: 's16',
    name: 'CI/CD (GitHub / GitLab)',
    category: 'devops',
    proficiency: 82,
    yearsOfExperience: 2,
    relatedProjects: ['1', '3'],
    color: '#FF0000',
  },
  {
    id: 's17',
    name: 'AWS',
    category: 'devops',
    proficiency: 78,
    yearsOfExperience: 1,
    relatedProjects: ['1'],
    color: '#FF0000',
  },
  {
    id: 's18',
    name: 'Git',
    category: 'devops',
    proficiency: 95,
    yearsOfExperience: 3,
    relatedProjects: ['1', '2', '3', '4'],
    color: '#FF0000',
  },
  // Mobile & Other
  {
    id: 's19',
    name: 'React Native',
    category: 'frontend',
    proficiency: 80,
    yearsOfExperience: 1,
    relatedProjects: [],
    color: '#8B00FF',
  },
  {
    id: 's20',
    name: 'Progressive Web Apps',
    category: 'frontend',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['2'],
    color: '#8B00FF',
  },
  // CMS & E-commerce
  {
    id: 's21',
    name: 'WordPress',
    category: 'other',
    proficiency: 88,
    yearsOfExperience: 3,
    relatedProjects: ['3'],
    color: '#8B00FF',
  },
  {
    id: 's22',
    name: 'WooCommerce',
    category: 'other',
    proficiency: 85,
    yearsOfExperience: 2,
    relatedProjects: ['3'],
    color: '#8B00FF',
  },
  {
    id: 's23',
    name: 'Shopify',
    category: 'other',
    proficiency: 82,
    yearsOfExperience: 2,
    relatedProjects: ['3'],
    color: '#8B00FF',
  },
  {
    id: 's24',
    name: 'SEO / SEM',
    category: 'other',
    proficiency: 80,
    yearsOfExperience: 2,
    relatedProjects: ['3'],
    color: '#8B00FF',
  },
];

export const mockTimeline: TimelineEvent[] = [
  {
    id: 't1',
    type: 'work',
    title: 'Director CTO Valientes',
    organization: 'Valientes',
    description:
      'Responsable de la dirección técnica y liderazgo de un equipo de 5 desarrolladores. Diseño y ejecución de soluciones tecnológicas escalables, automatización y soporte técnico de infraestructuras tecnológicas. Integración de herramientas de IA para optimizar procesos.',
    startDate: '2024-04-01',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'IA', 'DevOps'],
    current: true,
  },
  {
    id: 't2',
    type: 'work',
    title: 'Full Stack Developer | Perfil IT',
    organization: 'Perfil IT',
    description:
      'Diseño y desarrollo de aplicaciones web integradas con IA. Creación de arquitecturas escalables, optimización de bases de datos SQL y NoSQL, configuración de entornos de desarrollo y producción. Establecimiento de plantillas de CI/CD para proyectos.',
    startDate: '2024-11-21',
    endDate: '2025-04-01',
    tech: ['Next.js', 'NestJS', 'PostgreSQL', 'MongoDB', 'Docker', 'CI/CD'],
    current: false,
  },
  {
    id: 't3',
    type: 'work',
    title: 'Desarrollador Web | Siu Lucero',
    organization: 'Siu Lucero',
    description:
      'Desarrollo de soluciones de e-commerce con WooCommerce y Shopify. Enfoque en optimización de rendimiento, gestión de inventarios y mejora de experiencia de usuario. Implementación de soluciones de gestión de datos e integración de APIs.',
    startDate: '2023-06-20',
    endDate: '2024-11-21',
    tech: ['WordPress', 'WooCommerce', 'Shopify', 'PHP', 'JavaScript', 'MySQL'],
    current: false,
  },
  {
    id: 't4',
    type: 'work',
    title: 'Desarrollador Web | OWGZU Chile',
    organization: 'OWGZU Chile',
    description:
      'Diseño y desarrollo de plataformas web para clientes. Optimización de rendimiento de sitios web, configuración de APIs, y mejora de experiencia de usuario. Trabajo en equipo con diseñadores y clientes para cumplir objetivos.',
    startDate: '2022-03-15',
    endDate: '2023-06-20',
    tech: ['React', 'Laravel', 'MySQL', 'API REST', 'Git'],
    current: false,
  },
  {
    id: 't5',
    type: 'education',
    title: 'Ingeniería en Desarrollo de Software',
    organization: 'Instituto Profesional AIEP',
    description:
      'Formación en desarrollo de software, arquitectura de sistemas, bases de datos y metodologías ágiles. Enfoque en desarrollo web full stack y buenas prácticas de programación.',
    startDate: '2020-10-01',
    current: false,
  },
  {
    id: 't6',
    type: 'achievement',
    title: 'Data Analyst with Python',
    organization: 'DataCamp',
    description: 'Certificación en análisis de datos con Python, manipulación de datos y visualización.',
    startDate: '2024-01-01',
    current: false,
  },
  {
    id: 't7',
    type: 'achievement',
    title: 'Full Stack Switching',
    organization: 'Desafío Latam',
    description: 'Bootcamp intensivo de desarrollo Full Stack con enfoque en tecnologías modernas.',
    startDate: '2023-01-01',
    current: false,
  },
];

export const mockAnalytics: AnalyticsSummary = {
  totalVisits: 12547,
  uniqueVisitors: 8932,
  topProjects: [
    { id: '1', views: 3421 },
    { id: '4', views: 2876 },
    { id: '2', views: 2103 },
  ],
  topSkills: [
    { id: 's1', interest: 4521 },
    { id: 's2', interest: 3987 },
    { id: 's3', interest: 3654 },
  ],
  recentActivity: [
    { action: 'Project viewed: Neural Marketplace', timestamp: new Date().toISOString() },
    { action: 'Contact form submitted', timestamp: new Date(Date.now() - 3600000).toISOString() },
    {
      action: 'Skills page visited',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};
